from lib import *
notes={
'Brazoria':"Targeted pass 3 2026-10-02 (targeted3-B): no election decided; tag and results unchanged. Tried: (1) wayback-data targeted Wayback captures now present (4 election-window captures: polling-places-election-day 2024-11-05 23:44 CST, polling-places-early-voting 2024-11-06 03:11 CST, candidate-information 2026-03-03 19:50 CST, polling-places-election-day 2026-05-26 21:49 CDT); none contains results, only the navigation link '/departments/elections/election-results'. targeted/archives (archive.today timemaps) empty; Memento refused. (2) https://www.brazoriacountytx.gov/departments/elections also returns HTTP 403 (same protection). (3) One search found only canvass-time CivicPlus documents (showpublisheddocument version ticks decode to 2026-03-16) on the protected host. (4) Check 4: KPRC click2houston '2026 primary elections results for brazoria county' (dateModified 2026-03-04T04:27:47Z) shows county totals only from a Graham Digital feed (elex.grahamdigital.com bti.xml, xml_update_time '03/05/2026 02:28pm'), no per-precinct votes. Sweep pending.",
'Ellis':"Targeted pass 3 2026-10-02 (targeted3-B): no election decided; tag and results unchanged. Tried: (1) livevoterturnout ENR page source (ellistxenr/4/en/Index_4.html, 6.7 MB static HTML): all results are embedded in the page; the only data file it loads is '../ellistxenr_4.txt' (a GeoJSON map layer for 'Districts'); the shared script LiveResultsScripts_v4.1.js returns 404; no update history or per-update files exist, and today's copy is the canvass state ('Website Updated: 3/10/2026 2:10:56 PM'). (2) archive.org/wayback/available (reachable) shows a Wayback capture of ellistxenr/4/en/Index_4.html at 20260304054915 UTC (11:49 PM CST, election night), but web.archive.org replays and archive.ph are refused by the fetch module (robots_disallowed_or_unreachable), so its content cannot be read here; no capture near election night for ellistxenr/5 (Democratic primary), /9 or /10 (runoff). This 2026 primary capture is the best lead for the targeted Wayback harvest (not yet on the branch for Ellis). (3) Check 4 search found only county notices and a 'Preliminary Election Reconciliation Unofficial Totals' PDF (DocumentCenter/View/22968, CreationDate Mar 4 2026 05:07 UTC; turnout only, no candidate votes, no Last-Modified header). Sweep pending.",
'Potter':"Targeted pass 3 2026-10-02 (targeted3-B): no election decided; tag and results unchanged. Tried: (1) all report files for the three elections on Archived Election Results (Wix _files/ugd, which returns real Last-Modified values): 2024 general 'General Cumulative' (Official Results, Run Date 11/20/2024, Last-Modified Fri, 22 Nov 2024 19:04:09 GMT) and 'General Pct. x Pct.' (Official Results, Run Date 11/22/2024, Last-Modified Fri, 22 Nov 2024 19:07:59 GMT); 2026 primary 'Republican Cumulative' (Official Results, Run Date 03/10/2026, Last-Modified Wed, 11 Mar 2026 19:09:58 GMT); 2026 runoff 'Republican Cumulative' (Official Results, Run Date 06/02/2026, Last-Modified Thu, 04 Jun 2026 21:01:24 GMT). All canvass-time; no election-night file is listed. An unlisted Wix file found by search (abcbbe_2d48...pdf) is a 2024 polling-place list. (2) Check 4: NewsChannel 10 runoff-night article embeds 'Potter Co. Election Results' on Scribd, but the Scribd page exposes no readable text or run time (only an AI summary), so it cannot be used. Wayback harvest for co.potter.tx.us failed (connection refused); no targeted archive data; sweep pending.",
'Medina':"Targeted pass 3 2026-10-02 (targeted3-B): no election decided; tag and results unchanged. Tried: (1) Elections 2026 page re-read: still only Official files for the 2026 primary and runoff. A web search result title shows the page once listed '05/26/2026 May 26, 2026 Joint Primary Runoff - Election Day, Early Voting & Absentee - Unofficial Results' (search text only, not evidence); following the page's naming pattern of the May 2 local election ('ED EV AB - UNOFFICIAL.pdf'), one try each at '2026 May Primary Runoff/Results/ED EV AB - UNOFFICIAL.pdf' and '2026 March Primary/Results/Unofficial Cumulative Results.pdf' returned HTTP 404, so the election-night files are gone. (2) Wayback harvest of medinacountytexas.org was refused (robots); no targeted archive data for Medina; sweep pending. Lead: the runoff 'Unofficial Results' file was a county-totals report by its title; an archived copy with its upload time could support LATER for the runoff.",
}
for c,n in notes.items():
    d=load(c); save(c,d,n)
