from lib import *
# ---------------- Van Zandt
c='Van_Zandt'; d=load(c)
VP="https://www.vanzandtcounty.org/upload/page/2685/2026/Primary%2003032026/unofficial%20final%20Cumulative%20Results-3-3-2026%2011-23-52%20PM.pdf"
VPAGE="https://www.vanzandtcounty.org/page/vanzandt.Elections"
VR="https://www.vanzandtcounty.org/upload/page/12440/rep_pct_by_pct622026_040937_pm.pdf"
VRC="https://www.vanzandtcounty.org/upload/page/2685/cumulative_results622026_041109_pm.pdf"
V24="https://www.vanzandtcounty.org/upload/page/2707/2024cont/cumulative_results11142024_045640_pm.pdf"
VH="https://www.vanzandtcounty.org/default.aspx"
d['elections']['2026_primary'].update({"result":"LATER","check":"2","county_totals_first_seen":"2026-03-03 23:23 CT",
 "precinct_first_seen":"","night_updates_with_precinct_numbers":"0","evidence_url":VP,
 "fact":"County file 'unofficial final Cumulative Results-3-3-2026 11-23-52 PM.pdf' (under /upload/page/2685/, the home page's upload folder) reads 'Cumulative Results Report VAN ZANDT COUNTY, TEXAS Unofficial Results Ballots Cast PRIMARY ELECTION 11415 March 2026 Primary Election Precincts Reporting 18 of 18 = 100.00% Run Time 11:23 PM 3/3/2026 Run Date 03/03/2026' with Absentee, Early Voting and Election Day county totals; server Last-Modified Wed, 04 Mar 2026 05:32:31 GMT (11:32 PM CST). It is a county-totals report printed and uploaded on election night, named the final unofficial posting. No precinct-level report for this primary was found: the Elections page's 'March 3rd 2026 Primaries' section today lists no results at all (only polling places, sample ballots, notices and daily check-ins). Precinct numbers with election-day votes were not seen on election night: LATER (precinct results not found online at all for this primary)."})
d['elections']['2026_runoff']['fact']="Elections page 'May 26 2026 Runoff Elections' lists 'Final Results' = rep_pct_by_pct622026_040937_pm.pdf ('rep pct by pct Official Results ... Run Time 4:09 PM 5/26/2026 Run Date 06/02/2026', Last-Modified Thu, 04 Jun 2026 14:48:46 GMT) and /upload/page/2685/cumulative_results622026_041109_pm.pdf (Official, Run Date 06/02/2026, Last-Modified Thu, 04 Jun 2026 14:43:24 GMT). Precinct numbers appeared after election night, but no election-night county-totals file survives, so LATER cannot be applied (rule 43). Sweep pending."
d['elections']['2024_general']['fact']="Elections page 'November 5th Elections' lists 'Official Results' = cumulative_results11142024_045640_pm.pdf ('Cumulative Results Report ... Unofficial Results ... official election results ... Run Time 4:56 PM 11/5/2024 Run Date 11/14/2024', Last-Modified Fri, 15 Nov 2024 14:25:47 GMT), a reconciliation form and a preliminary reconciliation. No election-night file survives. Sweep pending."
d['results_url']=VPAGE; d['platform']='county_pdfs'; d['evidence_url']=VP
d['sources']=[s for s in d['sources']]+[
 src(VPAGE,"March 3rd 2026 Primaries ... Polling Locations ... EARLY VOTING HOURS Democrat ... PRECINCT 1 SAMPLE BALLOT ... Notice of Election ... 02.17 Daily Check-ins; May 26 2026 Runoff Elections ... Democratic ... Final Results ... Republican ... Final Results; November 5th Elections ... Official Results ... Reconciliation Form (Final) ... Preliminary Reconciliation","County Elections page lists no primary results; runoff and general only final or official files"),
 src(VP,"Cumulative Results Report VAN ZANDT COUNTY, TEXAS Unofficial Results ... Precincts Reporting 18 of 18 = 100.00% Run Time 11:23 PM 3/3/2026 Run Date 03/03/2026 (Last-Modified Wed, 04 Mar 2026 05:32:31 GMT; PDF CreationDate Wed Mar 4 05:23:55 2026 UTC)","2026 primary county totals printed and uploaded on election night"),
 src(VR,"rep pct by pct Official Results VAN ZANDT COUNTY, TEXAS ... PRIMARY RUNOFF ELECTION ... Run Time 4:09 PM 5/26/2026 Run Date 06/02/2026 (Last-Modified Thu, 04 Jun 2026 14:48:46 GMT)","runoff precinct numbers posted after election night"),
 src(VRC,"Cumulative Results Report VAN ZANDT COUNTY, TEXAS Official Results ... Run Time 4:10 PM 5/26/2026 Run Date 06/02/2026 (Last-Modified Thu, 04 Jun 2026 14:43:24 GMT)","runoff county totals file is canvass-time"),
 src(V24,"Cumulative Results Report ... Run Time 4:56 PM 11/5/2024 Run Date 11/14/2024 (Last-Modified Fri, 15 Nov 2024 14:25:47 GMT)","2024 general file is canvass-time"),
 src(VH,"/upload/page/2685/2026/Burnban08102026.pdf ... /upload/page/2685/FY27 Adopted Budget 09232026c.pdf","upload folder 2685 belongs to the home page; election-night files were posted there and are no longer linked"),
 src("websearch:?q=vanzandtcounty.org%20upload%20page%202685%20unofficial%20cumulative%20results%20runoff%205-26-2026","Cumulative Results 5 26 2026 09 39 16 PM ED Unofficial (another county, page 11725)","search for a Van Zandt runoff election-night file found none",via='websearch'),
]
save(c,d,"Targeted pass 3 2026-10-02 (targeted3-B): www.vanzandtcounty.org is now reachable through the fetch module. The 2026 primary is now LATER by check 2: the file found by the earlier search, 'unofficial final Cumulative Results-3-3-2026 11-23-52 PM.pdf', is a county-totals Cumulative report printed 11:23 PM and uploaded 11:32 PM CST on election night, and no primary precinct report is posted anywhere on the Elections page. The 2026 runoff (precinct-by-precinct 'Final Results' uploaded Jun 4 2026) and 2024 general (official cumulative uploaded Nov 15 2024) stay UNDETERMINED because no election-night county-totals file survives. Two searches for runoff/general election-night files found none. Wayback CDX for vanzandtcounty.org was refused (robots) in the harvest; no targeted archive data; sweep pending.",
 "Only the 2026 primary is determined (LATER, check 2: an election-night Unofficial Cumulative county-totals report and no precinct report), so the tag is COUNTY_ONLY_PRECINCT_AT_CANVASS at confidence low under the single-election rule.")

# ---------------- Randall
c='Randall'; d=load(c)
RP="https://www.randallcounty.gov/183/Election-Results"
NC="https://www.newschannel10.com/2026/05/27/see-may-2026-joint-primary-election-runoff-results-here/"
SC="https://www.scribd.com/document/1043721264/Randall-Co-Republican-Cumulative-5-26-2026-08-43-35-PM"
d['elections']['2026_runoff'].update({"result":"LATER","check":"4","rule":"check4","county_totals_first_seen":"2026-05-26 20:43 CT",
 "precinct_first_seen":"","night_updates_with_precinct_numbers":"0","evidence_url":SC,
 "fact":"NewsChannel 10 (KFDA) article 'See May 2026 Joint Primary Election runoff results here' (article:published_time 2026-05-27T01:58:16Z = 8:58 PM CDT, modified 03:18:35Z = 10:18 PM CDT) embeds under 'Randall Co. Election Results' a Scribd copy of the county's report 'Randall Co. Republican Cumulative-5-26-2026 08-43-35 PM', which reads 'Republican Cumulative Run Time Run Date 8:43 PM 05/26/2026 RANDALL COUNTY, TEXAS 2026 Joint Primary Runoff Election 5/26/2026 Page 1 Unofficial Results Registered Voters 10678 of 101083 = 10.56% Polling Places Reporting 18 of 18 = 100.00%' with Absentee, Early Voting and Election Day county totals. This is a county-totals report printed on election night. The county's Election Results page today lists for this runoff only 'Official Republican Cumulative Report', 'Official Democratic Cumulative Report', 'Official Democratic Canvass Report', 'Official Republican Canvass Report' (the Canvass reports are the precinct-level reports) and reconciliation forms; no election-night precinct report was found anywhere. LATER under rule 43 via a third-party copy; it does not show whether the county itself posted the cumulative online that night."})
d['elections']['2024_general']['fact']="Election Results page (now reachable) lists for 'General Election November 5, 2024' only 'Official Canyon ISD Canvass Report', 'Official City of Amarillo Canvass Report', 'Official Randall County Canvass Report', 'Official Wildorado ISD Canvass Report', 'Official Canvass Results', 'Official Cumulative Results' (CivicPlus DocumentCenter). No election-night file survives. Wayback harvest of randallcounty.com: 0 captures. Sweep pending."
d['elections']['2026_primary']['fact']="Election Results page lists for '2026 Joint Primary Election March 3, 2026' only 'OFFICIAL DEM Canvass Results-3-10-2026 10-51-03 AM', 'OFFICIAL REP Canvass Results-3-10-2026 10-50-36 AM', 'Official Republican Cumulative Results', 'Official Democratic Cumulative Results' and reconciliation forms. No election-night file survives; no third-party election-night copy found. Sweep pending."
d['results_url']=RP; d['platform']='county_pdfs'; d['evidence_url']=SC
d['sources']+=[
 src(RP,"2026 Joint Primary Runoff Election Official Republican Cumulative Report Final Election Reconciliation Report Official Democratic Cumulative Report Official Democratic Canvass Report Official Republican Canvass Report ... 2026 Joint Primary Election March 3, 2026 ... OFFICIAL DEM Canvass Results-3-10-2026 10-51-03 AM ... General Election November 5, 2024 ... Official Randall County Canvass Report ... Official Cumulative Results","County results page lists only official files for the three elections"),
 src(NC,"AMARILLO, Texas (KFDA) - The results for the runoff election for Tuesday, May 26, are rolling in. ... Randall Co. Election Results ... Randall Co. Republican Cumulative-5-26-2026 08-43-35 PM by NewsChannel 10 (article:published_time 2026-05-27T01:58:16.922Z; article:modified_time 2026-05-27T03:18:35.351Z)","Election-night news article embedding the county cumulative report"),
 src(SC,"Republican Cumulative Run Time Run Date 8:43 PM 05/26/2026 RANDALL COUNTY, TEXAS 2026 Joint Primary Runoff Election 5/26/2026 Page 1 Unofficial Results Registered Voters 10678 of 101083 = 10.56% Polling Places Reporting 18 of 18 = 100.00%","County-totals report printed on runoff election night"),
 src("websearch:?q=randall%20county%20potter%20county%20election%20night%20results%20by%20precinct%202026%20primary%20amarillo","See May 2026 Joint Primary Election runoff results here https://www.newschannel10.com/2026/05/27/...","located the NewsChannel 10 article",via='websearch'),
]
save(c,d,"Targeted pass 3 2026-10-02 (targeted3-B): www.randallcounty.gov is now reachable; /183/Election-Results lists only Official Cumulative and Official Canvass (precinct) reports plus reconciliations for all three elections, and /166/Election-Administration has no other results link. Check 4 found a NewsChannel 10 runoff-night article (published 8:58 PM CDT) embedding the county's 'Republican Cumulative' report 'Unofficial Results' printed 8:43 PM 05/26/2026 (county totals). The 2026 runoff is set to LATER on that basis (check 4, rule check4): an election-night county-totals report and no election-night precinct report found; caveat: the copy came from a TV station, so it does not show the county posted it online itself. Searches found no comparable March 2026 or November 2024 election-night copy; those stay UNDETERMINED. Sweep pending.",
 "Only the 2026 runoff is determined (LATER from an election-night county Cumulative report embedded by NewsChannel 10, check 4), so the tag is COUNTY_ONLY_PRECINCT_AT_CANVASS at confidence low under the single-election rule.")
