import json
p="phase1/verification/Grayson.json"; d=json.load(open(p))
d["research_tag"]="COUNTY_ONLY_PRECINCT_AT_CANVASS"
d["agree"]=True
d["comparison_notes"]={
 "2024_general": "Same (LATER, check 2). Both rest on the same unlinked election-night county-totals file 'Election Day General November 5 2024 .pdf' (printed 11/05/2024 09:56PM, Last-Modified 04:03:28 GMT = 10:03 PM CST) and the Nov 19 official Pct. by Pct. report as the first precinct numbers; I confirmed the hash (8c2ee494...), times and that all 24 pages are county summaries. Both note the caveat that folder 0060 is not a complete record of election-night postings; I add that the same folder held an election-night unofficial precinct report for the May 3, 2025 election (Last-Modified 04 May 2025 02:38:21 GMT), so the county does sometimes post precinct reports on election night; none is known for Nov 2024, so condition (ii) of the DECISIONS 67 reading is met on present evidence.",
 "2026_primary": "Same (UNDETERMINED). Both found the unofficial primary files only as names (HTTP 404 or empty 'Document Open' pages) and only Official_*_2026 reports surviving. Research fact still says 'Check 3 pending'; the wayback-data branch now has a Grayson index with no captures (CDX empty), so check 3 is done with nothing found.",
 "2026_runoff": "Same (UNDETERMINED). Only official runoff files (folder 3854) found by both. Research fact text 'No 2026 runoff results listed on the elections pages' is superseded by its own pass 4 note (elec.history lists official runoff files); 'Check 3 pending' is stale as above.",
 "unsupported_or_stale_claims": "No research claim is contradicted by the cited sources. Stale: 'Check 3 pending' in the primary and runoff facts and 'origin/wayback-data not present' in notes (the branch exists; Grayson has no captures, 2024 CDX request refused). Not checkable: the Howe Enterprise article date ('runoff night'), since the fetch module refuses that host; it is not used for any result. Seed-URL 403 claim: my fetch of the seed URL returned a cached 200 that rendered the county homepage; immaterial."
}
json.dump(d, open(p,"w"), indent=1, ensure_ascii=False)

p="phase1/verification/Tom_Green.json"; d=json.load(open(p))
d["research_tag"]="COUNTY_ONLY_PRECINCT_AT_CANVASS"
d["agree"]=True
d["comparison_notes"]={
 "2024_general": "Same (UNDETERMINED). Both found only the Nov 27, 2024 official cumulative and precinct reports. Research's '110524finalOffCumulaRes.pdf' has the same content hash (59b54198...) as the results page's November_5_Cumulative_Results.pdf and Last-Modified Tue, 03 Dec 2024 15:23:48 GMT (confirmed in the fetch store).",
 "2026_primary": "Same (LATER, check 2), same file and times: 6thUnofficialCumulativeresults032026.pdf, county totals on all pages, Run Time 11:20 PM 03/03/2026, Last-Modified 05:52:19 GMT (11:52 PM CST); official precinct report uploaded Apr 1. On the 6th-update question: the file name shows five earlier election-night updates that are no longer online. I still hold that condition (ii) of the DECISIONS 67 reading is met: (ii) asks whether anything shows precinct numbers with election-day votes were posted that night, and nothing does; the missing files belong, by their name, to the same 'Unofficial Cumulative results' series (county totals), and the 6th is the final unofficial count (its 16,497 ballots equal the election-night Preliminary Election Reconciliation), so a precinct release that night would most likely sit alongside it and none is known; the runoff, with two surviving election-night updates and no precinct report, shows the same practice. The gap (updates 1 to 5 unread) is a real limit, which research also states ('removed files cannot be ruled out'), but under the rule as written absence of a precinct report is what (ii) requires, not proof that none existed. If the owner wants (ii) to require that every election-night update be readable, this election would become UNDETERMINED and the county tag would fall to low confidence on the runoff alone (still COUNTY_ONLY_PRECINCT_AT_CANVASS).",
 "2026_runoff": "Same (LATER, check 2), same two files: report 2.pdf (Run Time 8:05 PM, Last-Modified 01:26:52 GMT = 8:26 PM CDT) and final unofficial.pdf (Run Time 8:49 PM, Last-Modified 02:36:59 GMT = 9:36 PM CDT), both county totals; official precinct report Jun 8.",
 "unsupported_or_stale_claims": "Minor transcription error: research quotes report 2.pdf as 'KEN PAXTON Election Day 549, Total 3,154'; the page image shows Total 3,194 (63.88%), which equals 272 + 2,373 + 549. Does not affect the result. Stale: notes say 'Check 3 pending (origin/wayback-data branch not found)'; the branch now holds a Tom Green index with no captures. Everything else checked (upload times, run times, CreationDates, San Angelo LIVE datePublished 2026-03-04T12:07:20-0600 and 2026-05-26T20:37:06-0500, official precinct report dates) is supported by the cited sources."
}
json.dump(d, open(p,"w"), indent=1, ensure_ascii=False)
