import json,sys
sys.path.insert(0,'.')
from phase1.schema import validate_v2
P="Targeted pass 3 2026-10-02 (targeted3-F): "
COMMON=" No targeted archives, targeted Wayback or sweep file for this county on wayback-data. No result changed."
N={
"Milam":"wayback-data harvest: CDX failed for 2024_general and 2026_primary (connection refused); the one 2026_runoff capture (2026-05-26 19:51 CDT, departments/elections_and_voter_registrar/index.php) shows only the elections home page with an 'Election Results' menu link and no results files. Current Election Results page unchanged: only post-canvass scans (2024 General, 2026 PRIMARY) and no runoff file; Revize ?t= stamps (t=202507241306320, t=202605071228540) match the known re-upload dates. One web search for Cameron Herald or Rockdale Reporter precinct results; the Cameron Herald article links it returned (node/216598, node/211043) give HTTP 404. web.archive.org is unreachable from this environment (fetch module: robots_disallowed_or_unreachable), so no direct Wayback lookups.",
"Trinity":"wayback-data harvest: CDX failed for all three elections (robots_disallowed_or_unreachable), no captures. Re-read the Elections Administrator page and the Archived Election Results page: still only May 26, 2026 runoff canvass .xls, PEHCA worksheets and 'Post Election Runnoff' PDF, and archived 2016, 2018 and 2022 canvass files; nothing for the 2024 general or 2026 primary. One web search found no Trinity County, Texas election-night results page (results were for Trinity County, California).",
"Reeves":"wayback-data harvest: CDX failed for all three elections (connection refused or TLS timeout), no captures. Retried the results archive page once: still HTTP 403 (bot protection, not worked around). Two web searches found no Reeves County results page, vendor site or news page with precinct numbers. web.archive.org is unreachable from this environment, so no direct Wayback lookups.",
"Hamilton":"wayback-data harvest: CDX failed for 2024_general (connection refused) and returned no captures for 2026_primary and 2026_runoff (target host was the dead seed domain hamiltoncountytx.org). Re-read hamiltoncountytx.gov/page/hamilton.elections and opened the election-day files '3-3-2026.pdf' (Last-Modified Wed, 04 Mar 2026 17:09:57 GMT) and '5-26-2026.pdf' (Last-Modified Thu, 28 May 2026 15:17:21 GMT): page images show 'Election Day Voting in Person' rosters (voter names), not results. No election-night results file exists on the page. Verifier disagreement on 2026_runoff is already resolved (both UNDETERMINED).",
"Winkler":"wayback-data harvest: CDX failed for all three elections (robots_disallowed_or_unreachable), no captures. Re-listed the /213/Elections page: results-related files are 'Unofficial Results - General Election (PDF)' (View/380), 'Official Election Results (PDF)' (View/378), 'Unofficial Results March 3, 2026' (View/783), 'Summary results 2026 runoff election' (View/803) and 'Precinct Results 2026 Primary runoff election' (View/808, a sample ballot per the earlier pass); CivicPlus DocumentCenter still gives no upload time, and every unofficial scan was created after election night, so no election-night posting can be shown.",
"Dallam":"wayback-data harvest: CDX ran for all three elections and found no election-night captures of dallam.org. Site is hand-written HTML, not WordPress (/wp-json/wp/v2/media returns 404). The vote page's only results links remain 'Election Results' and 'Resultados Electorales' to SOS pages. Lead only: the posted counting plan countplan.pdf (Last-Modified Wed, 04 Oct 2023 21:46:11 GMT, scanned; read from page image) says 'Unofficial election results will be released via Sherman County's Elections Department webpage, beginning no earlier than 7:00p.m. on Election Day', evidently template text from Sherman County; it decides nothing for these elections. NONE still lacks per-election positive evidence.",
"Sherman":"wayback-data harvest: CDX ran for all three elections and found no election-night captures of co.sherman.tx.us. Refetched /page/Elections.2026 and /page/Elections.2025.and.Earlier with --refresh, and tried /page/sherman.Elections.2026 and /page/sherman.Elections.Home: all return HTTP 200 with the homepage body (same content hash 000f110564a3e052ae39ff1caf06176ce70aee60524ea6598b14ec399f82b24e), so no election files can be read. Lead only: Dallam County's posted counting plan (template from Sherman County) says 'Unofficial election results will be released via Sherman County's Elections Department webpage, beginning no earlier than 7:00p.m. on Election Day. Election Day results will be released incrementally as processed through acceptance and tabulation until all results are in.' (2023 document, no precinct detail).",
"Borden":"wayback-data harvest: CDX returned no captures for 2024_general and failed for 2026_primary and 2026_runoff (connection refused). Read Last-Modified for every results file: 2026 primary official xls files Last-Modified Wed, 18 Mar 2026 15:48:23 and 15:47:29 GMT; runoff 'OFFICIAL RESULTS FOR DEMOCRATIC PRIMARY RUNOFF MAY 26, 2026' (DEMOCRATIC PRIMARY RUNOFF.pdf) is a scan created Wed May 27 01:08:18 2026 UTC (8:08 PM CDT election night) whose page image shows a per-precinct table (precincts 1A, 1B, 2, 3, 4, EARLY, ABBM; e.g. 'VIKKI GOODWIN 0 0 0 0 0 0 2 2 0 2'), but Last-Modified Thu, 18 Jun 2026 16:17:34 GMT, so under rule 47 it cannot show election-night posting; the Republican runoff scan (Black and White0430.pdf) was created Jun 8 and uploaded Jun 18. 2026_runoff stays UNDETERMINED.",
}
for c,t in N.items():
    p=f'phase1/evidence/{c}.json'
    d=json.load(open(p))
    d['notes']=d['notes'].rstrip()+" "+P+t+COMMON
    validate_v2(d)
    s=json.dumps(d,indent=1,ensure_ascii=False)
    assert all(ord(ch)<128 for ch in s),c
    open(p,'w').write(s)
    print(c,d['tag'],d['confidence'])
