import json,sys
sys.path.insert(0,'.')
from phase1.schema import compute_tag, compute_confidence, validate_v2
NOTES={
'Smith':"Targeted pass 6 2026-10-03 (targeted6-C): no election changed; tag and confidence unchanged. Tried: (1) wayback-data re-read: phase1/targeted/sweep/Smith has 0 versions for all three elections (CDX queries timed out or returned 0 rows); no new archive data. (2) County party sites: 4 web searches found no Smith County Republican or Democratic party website (only a Facebook directory listing), so no party upload log to read. (3) Tyler Morning Telegraph (tylerpaper.com, WordPress) media upload log via /wp-json/wp/v2/media for Nov 5-6 2024, Mar 3-4 2026 and May 26-27 2026: no PDF or document uploads; the 2024 items are image attachments re-dated in a May 2025 migration ('www.smith-county.com - 1' at 6:00 PM is attached to a turnout story); the four primary-night 'Screenshot' PNGs (uploaded 8:16 PM, 9:55 PM, 11:42 PM, 12:25 AM) were opened and are candidate photos, not results; runoff-night screenshots are titled with candidate names. (4) KETK (ketk.com, WordPress) media log for the three nights: images only, no PDF; the primary live post 'East Texas Primary Election Results 2026: Live Updates and Winners' (REST API, published 2026-03-03T18:39:46, modified 2026-03-04T21:26:19) holds only election-hub widgets (wp-json/election-hub/v1/widget/...) with race totals; the article HTML answered HTTP 403 (not worked around). (5) digital-release.ketk.com/?p=1193093 is a 2022 candidate list. (6) Searches for GitHub scrapers and tylerpaper/KLTV precinct copies found nothing for Smith. No third-party per-precinct election-night copy found for any election.",
'Randall':"Targeted pass 6 2026-10-03 (targeted6-C): no election changed; tag and confidence unchanged. Tried: (1) wayback-data re-read: phase1/targeted/sweep/Randall has 0 versions for all three elections. (2) County party sites: searches found no Randall County Republican or Democratic party website (only news on the party chair and a joint Democratic headquarters), so no party upload log to read. (3) City of Amarillo WordPress media log (index.php?rest_route=/wp/v2/media) for Mar 3-5 2026 (MPO newsletter and two 2023 feasibility PDFs only) and May 26-28 2026 (one MPO PDF): no election report. (4) KAMR (myhighplains.com, WordPress) media log for Nov 5-6 2024, Mar 3-4 2026 and May 26-27 2026: AP and station images only, no PDF or results document. (5) KFDA NewsChannel 10: sitemap index and section sitemaps list only the latest stories (no election section), so no March 2026 or November 2024 results article could be located; the runoff article's Scribd embeds were re-listed (Deaf Smith, Carson, Hansford, Potter and the Randall 'Republican Cumulative'), none a Randall per-precinct report. (6) Searches for Canyon ISD November 2024 results and GitHub scrapers found no per-precinct election-night copy. The Amarillo Globe-News primary articles on aol.com answer HTTP 404.",
'Potter':"Targeted pass 6 2026-10-03 (targeted6-C): no election changed; tag and confidence unchanged. Tried: (1) wayback-data re-read: phase1/targeted/sweep/Potter has only two Wix API JSON captures from 2026-03-21 (access-tokens, tag-manager), no results files. (2) County party sites: searches found no Potter County Republican or Democratic party website. (3) The NewsChannel 10 runoff article's 'Potter Co. Election Results' Scribd document (cached page) has page_count 2 and its description reads 'The document presents the unofficial results of the Joint Primary Runoff Election in Potter County, Texas, held on May 26, 2026. It includes vote counts and percentages for various positions ... detailing absentee, early, and election day voting' - a two-page county-totals report, not per-precinct, and a third-party copy of county totals cannot decide LATER (DECISIONS 62). (4) A further unlisted Wix file found by search (abcbbe_a5ba10b9...pdf, Last-Modified Mon, 01 Apr 2024 19:16:33 GMT) is a May 28 2024 Republican runoff sample ballot. (5) KAMR and City of Amarillo WordPress media logs for the election nights (see Randall note) hold no election report. (6) Amarillo Globe-News primary-night articles on aol.com answer HTTP 404; no other per-precinct election-night copy found.",
}
for c,n in NOTES.items():
    p=f'phase1/evidence/{c}.json'; d=json.load(open(p))
    before=(d['tag'],d['confidence'])
    d['notes']=d['notes'].rstrip()+' '+n
    tag,_=compute_tag(d['elections']); assert tag==d['tag']; assert compute_confidence(d)==d['confidence']
    for bad in ['—','–']: assert bad not in d['notes']
    validate_v2(d)
    fmt={'Smith':(1,''),'Randall':(1,'\n'),'Potter':(2,'\n')}[c]
    open(p,'w').write(json.dumps(d,indent=fmt[0],ensure_ascii=False)+fmt[1])
    print(c,before,d['tag'],d['confidence'])
