import json, sys
sys.path.insert(0, '.')
from phase1.schema import validate_v2, compute_tag, compute_confidence

NOTES = {
"Wichita": "Targeted pass 6 2026-10-03 (targeted6-D): no election changed. New lead from the archive sweep (wayback_branch, phase1/targeted/sweep/Wichita): the county's WordPress sitemap of 'election_stats' posts (one post per race), archived 20241120213038 (sha256 0cfcefd5), lists 37 race posts with lastmod between 2024-11-05T22:04:45-06:00 and 2024-11-05T22:40:07-06:00 (e.g. 'https://wichitacountytx.com/election_stats/president-vice-president/ 2024-11-05T22:31:53-06:00'); the same sitemap archived 20260323081712 lists the 2026 primary race posts with lastmod 2026-03-03T21:53:42-06:00 to 2026-03-03T22:47:50-06:00 (e.g. 'https://wichitacountytx.com/election_stats/county-judge-republican-party/ 2026-03-03T21:58:39-06:00'), plus six 15th Court of Appeals posts modified 2026-03-04 08:09 to 08:15; the 2024 posts no longer appear there. So the county edited a per-race results post for every race on both election nights and did not edit them again before the captures, but the post contents (county totals only, or per-precinct numbers) are not saved anywhere readable here; the archived copies requested by pdf-probe run 4 (phase1/targeted/pdfs) had not landed when this pass finished (run still pending), so neither LATER nor END can be decided. No runoff capture of the sitemap exists in the sweep. Check 4 (third parties): five web searches (recorded) found no Wichita County Republican or Democratic party website and no GitHub or civic scrape; KAUZ 2026 primary story (refetched, hash f188d1a1, datePublished 2026-03-04T00:47:40Z) and KAUZ 'Brooks defeats Barron for City Council District 2' (hash e4a12a89, 10:40 PM CST Nov 5 2024, 'Out of reported results so far, Brooks has accumulated 1,791 to Barron's 1,157 votes') give totals only; 929nin.com 'Election Night Results' is from 2014 (hash fbfef1fb) and its wp-json returns 404; The Wichitan article (hash 07824902) is 2020 totals. County site not requested (bot protection). Lead for later: read the election_stats post copies when pdf-probe run 4 lands; a copy showing only county totals would need the rule 43 test, a copy showing per-precinct candidate votes the rule 47 test (sitemap lastmod is a server-side modification time, not a printed time).",
"Kerr": "Targeted pass 6 2026-10-03 (targeted6-D): no election changed. Tried: (1) wayback-data sweep (phase1/targeted/sweep/Kerr): no results files; the only saved files are an IRS mileage memo and burn plan templates; CDX for legacy.co.kerr.tx.us/elections/results/ returned 17 HTML rows between 2026-03-03 06:00 and 2026-03-24 06:00 UTC but the sweep lists and saves none of them, and the kerrcountytx.gov query timed out (Kerr is in the sweep rerun, still running at the end of this pass). (2) Check 4: two web searches (recorded) found no Kerr County party website or civic scrape. Hill Country Community Journal runoff story 'Lambert, Moose win runoff election; Middleton, Paxton dominate state races' (datePublished 2026-05-26T21:51:00-05:00, hash e1987239) gives county totals only ('The final tally for the local races in Commissioner Pct. 1 was Lambert with 1,358 votes and Hughes 769 votes') and says 'Final results were delayed until after 1 a.m. after a split vote of the Kerr County Republican Party forced hand-counting of election day only ballots'; its primary story 'Kerr County will see several new faces at county posts' (hash 9af0888d) is totals only. No per-precinct candidate votes with an election-night time found.",
"Nacogdoches": "Targeted pass 6 2026-10-03 (targeted6-D): no election changed. Tried: (1) wayback-data sweep (phase1/targeted/sweep/Nacogdoches): zero versions for all three elections (two CDX queries timed out; Nacogdoches is in the sweep rerun, still running at the end of this pass). (2) Check 4: three web searches (recorded) found no Nacogdoches County party website, no civic scrape, and no TV or newspaper per-precinct table; KETK 'Your Local Election HQ' Nacogdoches County page (hash 036e1d57) is the 2022 primary (datePublished 2022-03-01). A newtools.cira.state.tx.us page 3107 'JOINT PRIMARY ELECTION MARCH 3, 2026' election-day precinct PDF surfaced in search, but nothing in it names Nacogdoches County, so it is not attributed or used.",
"Walker": "Targeted pass 6 2026-10-03 (targeted6-D): no election changed. Tried: (1) wayback-data sweep (phase1/targeted/sweep/Walker): zero versions for all three elections (runoff CDX timed out; Walker is in the sweep rerun, still running at the end of this pass). (2) Check 4: Huntsville Item date-filtered RSS search (hashes 484dfca6, 1b11e32c, b5ad52eb) lists only 'Final Unofficial results released in Walker County' (published 2024-11-05T18:41:00-06:00, before polls closed, 175 words, no table, hash d874831d), 'Results for Walker County Primaries in March 3 election' (2026-03-04T10:41:00-06:00, after election night; body is paywall-encoded and was not decoded, hash 21dc2d01) and the runoff story at 2026-05-27 09:23 CDT (after election night). Three web searches (one shared across counties, recorded) found no Walker County party website and no GitHub or civic scrape. No per-precinct candidate votes with an election-night time found.",
}

for c, note in NOTES.items():
    p = f'phase1/evidence/{c}.json'
    d = json.load(open(p))
    assert 'targeted6-D' not in d['notes']
    d['notes'] = d['notes'].rstrip() + ' ' + note
    for bad in ['—', '–']:
        assert bad not in d['notes']
    validate_v2(d)
    json.dump(d, open(p, 'w'), indent=2, ensure_ascii=False)
    open(p, 'a').write('\n')
    print(c, d['tag'], d['confidence'])
